
# Marketing campaign DEV override with FAKE NID/VID for DEV TESTING
marketing:
    campaign:
        carPowerOTHRules:
            -
                name: DEVTest again CHANGE1
                startDateTime: 2016-10-31 00:00:01
                # a longer term end date for DEV testing
                endDateTime: 2020-12-31 00:00:01
                nid: N-OTH-2020
                vid: V-OTH-2020
                discountOffer: 0.50
            -
                name: 7/25/2018 Power Car V1
                startDateTime: 2018-07-19 00:00:01
                endDateTime: 2018-07-26 00:00:01
                nid: N-OTH-072518
                vid: V-OTH-072518-V1
                discountOffer: 0.50
            -
                name: 7/25/2018 Power Car V2
                startDateTime: 2018-07-19 00:00:01
                endDateTime: 2018-07-26 00:00:01
                nid: N-OTH-072518
                vid: V-OTH-072518-V2
                discountOffer: 0.50
            -
                name: 7/25/2018 Power Car V3
                startDateTime: 2018-07-19 00:00:01
                endDateTime: 2018-07-26 00:00:01
                nid: N-OTH-072518
                vid: V-OTH-072518-V3
                discountOffer: 0.50
            -
                name: 7/25/2018 Power Car V4
                startDateTime: 2018-07-19 00:00:01
                endDateTime: 2018-07-26 00:00:01
                nid: N-OTH-072518
                vid: V-OTH-072518-V4
                discountOffer: 0.50